### PR TITLE
Allow {module, function, args} for mixin

### PR DESCRIPTION
**Pull request by jechol**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [X] Features include unit/acceptance tests

### CODE REVIEW

**Comment by rgraff** [comment]
@jechol what's the use case here as opposed to just have a module mixin? Can you update the getting started guide with an example?

**Comment by jechol** [comment]
My use case is that I want to mix-in AshAdmin's admin section with name and resource group.


```
defmodule MyResource do
   ...
        paper_trail do
          mixin {MyPaperTrailMixin, :mixin, ["my_resource", :my_resource_group]}
        end
end

defmodule MyPaperTrailMixin do
  def mixin(name, group) do
    quote do
      admin do
        name unquote(name)
        resource_group unquote(group)
      end
    end
  end
end
```

**Comment by jechol** [comment]
@rgraff I updated guide to use {module, function, args} because it is more flexible than `use`.

**Comment by rgraff** [comment]
@jechol Looks good. Thank you for your contribution. 🎉

**Pull request merged**
