### PR TITLE
sort by version_inserted_at

### PR DESCRIPTION
**Pull request by jechol**
PR for #32 

### Contributor checklist

- [X] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by rgraff** [comment]
Looks good to me, though, it would be nice if this was configurable. I sort versions like a feed (in reverse chronological order)

**Comment by jechol** [comment]
@rgraff I changed it to reverse sorting, as it seemed more practical, just as you suggested.

**Comment by zachdaniel** [comment]
I think perhaps we should just make the sort configurable and default to no sort. Technically the sort option does add overhead when loading versions, and with people having potentially different ideas of how they should be sorted by default, it makes more sense to have it as a configuration option.

**Comment by zachdaniel** [comment]
This is now configurable w/ the relationship options configuration.

**Pull request closed without merging**
