### PR TITLE
feat: Add `table_name` and `store_resource_name?` DSL options.

### PR DESCRIPTION
**Pull request by jimsynz**
### feat: Add `table_name` DSL option.
When using a SQL-based data layer, allow the user to explicitly set the table name for version storage.

### feat: Add `store_resource_name?` DSL option.
Adds a `version_resource_name` attribute to the version resource which stores the name of the resource that is being changed.

### CODE REVIEW

**Comment by zachdaniel** [comment]
I'd rather have some kind of "version identifier" than the module name itself I think. Regardless, if storing that, we should also add a base filter on the version resource that it is what you're saying. That way you don't get versions from other resources.

**Comment by jimsynz** [comment]
> I'd rather have some kind of "version identifier" than the module name itself I think.

What if we store the resource's `short_name` rather than the module name?

> Regardless, if storing that, we should also add a base filter on the version resource that it is what you're saying. That way you don't get versions from other resources.

Good idea.

**Comment by zachdaniel** [comment]
The only issue with short name is that, unlike the module name it's not guaranteed to be unique, and if the module name changed, the default short name changes as well. If we use the resource name, changing the module name could require a migration of the largest tables in an app.

**Comment by jimsynz** [comment]
Okay, so we let them specify the resource name in this instance and default it to `short_name`

**Review by zachdaniel — APPROVED** [review]

**Pull request merged**
