### PR TITLE
allow all`Ash.Domain`  authorization types

### PR DESCRIPTION
**Pull request by tunchamroeun**
https://hexdocs.pm/ash/dsl-ash-domain.html#authorization-authorize

:always | :by_default | :when_requested

### Contributor checklist

- [ ] Bug fixes include regression tests
- [x ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by zachdaniel** [comment]
🤔 this would be a breaking change for folks relying on this behavior unfortunately. 

I'm not entirely sure that it ever makes sense to authorize the creation of a version object, it's not something that is ever meant to fail. Authorization should be done on the action in question.

**Comment by zachdaniel** [comment]
Given that this would be a non-trivial breaking change, I think we should have this discussion in a new issue, and we can discuss how we can accomplish what you're looking to accomplish and what changes would be necessary. Thank you for your proposal 🙇

**Comment by tunchamroeun** [comment]
Because version resource i

> 🤔 this would be a breaking change for folks relying on this behavior unfortunately.
> 
> I'm not entirely sure that it ever makes sense to authorize the creation of a version object, it's not something that is ever meant to fail. Authorization should be done on the action in question.

If I add
```elixir
authorization do
  authorize :always
end
```
with `authorize?: false` on versions resource will not work on create action (you can test or do I miss something?)

**Comment by zachdaniel** [comment]
Hmm...I don't *think* it would, as it pulls the domain off of the changeset in a hook: `domain: changeset.domain,`

**Comment by tunchamroeun** [comment]
I will reproduce the new issue about this.

**Pull request closed without merging**
